PAY_LOG_LEVEL: TRACE
auth:
    uri:
        whitelist: /**/gatewayconfig/provision/*/get
authServiceUri: https://aks-core-devint.hospitalityrevolution.com/auth-service
cors:
    allow:
        origin: http://localhost:3000
