PAY_LOG_LEVEL: TRACE
auth:
    uri:
        whitelist: /**/gatewayconfig/provision/*/get
authServiceUri: https://aks-core-devint.hospitalityrevolution.com/auth-service
cors:
    allow:
        origin: http://localhost:3000
logging:
    level:
        org:
            apache:
                cxf: info
metric:
    logger:
        delay: 86400000
mongodb:
    databaseName: dev_int_paymentgateway
    hostname: rguest-pay-dev-01.avg6p.azure.mongodb.net
    isAtlasInstance: true
    mainCollectionName: paymentgateway
    password: kz2F6mlbwrN48T7
    port: 27017
    requireAuth: true
    requireSsl: true
    username: sanchezm
    
paymentGatewayconfigService:
    base:
        uri: http://localhost:8080/pay-gateway-config-service
rguest:
    auth:
        oidc:
            jwkSetUrl: http://localhost:5000/.well-known/openid-configuration/jwks
    core:
        enable:
            javax:
                bean:
                    validation: false
server:
    servlet:
        context-path: /pay-gateway-config-service
service:
    runtimeFriendlyName: gatewayConfigServiceRuntimeUser
spring:
    application:
        name: gatewayconfig
    config:
        import: configserver:http://localhost:9001/pay-onboarding-controller
    dao:
        exceptiontranslation:
            enabled: false
    main:
        allow-bean-definition-overriding: true
        allow-circular-references: true
    profiles:
        active: dev    
